const propertyData = [
    {
      id: 1,
      name: "Sunny Side Villa",
      city: "Toronto",
      owner: "Alice Johnson",
      price: "$1,200,000",
      bedrooms: 4,
      bathrooms: 3,
      location: { latitude: 43.65107, longitude: -79.347015 },
    },
    {
      id: 2,
      name: "Urban Loft",
      city: "Vancouver",
      owner: "Bob Smith",
      price: "$950,000",
      bedrooms: 2,
      bathrooms: 2,
      location: { latitude: 49.282729, longitude: -123.120738 },
    },
    {
      id: 3,
      name: "Lakeview Retreat",
      city: "Montreal",
      owner: "Carla Martinez",
      price: "$850,000",
      bedrooms: 3,
      bathrooms: 2,
      location: { latitude: 45.501689, longitude: -73.567256 },
    },
    {
      id: 4,
      name: "Downtown Condo",
      city: "Calgary",
      owner: "David Green",
      price: "$600,000",
      bedrooms: 1,
      bathrooms: 1,
      location: { latitude: 51.044733, longitude: -114.071883 },
    },
    {
      id: 5,
      name: "Maplewood Estate",
      city: "Toronto",
      owner: "Evelyn Bennett",
      price: "$1,500,000",
      bedrooms: 5,
      bathrooms: 4,
      location: { latitude: 43.70011, longitude: -79.4163 },
    },
    {
      id: 6,
      name: "Seaside Cottage",
      city: "Vancouver",
      owner: "Michael Wright",
      price: "$1,100,000",
      bedrooms: 3,
      bathrooms: 2,
      location: { latitude: 49.25044, longitude: -123.137 },
    },
    {
      id: 7,
      name: "Heritage Home",
      city: "Ottawa",
      owner: "Olivia King",
      price: "$750,000",
      bedrooms: 3,
      bathrooms: 2,
      location: { latitude: 45.42153, longitude: -75.69719 },
    },
    {
      id: 8,
      name: "Skyline Residence",
      city: "Calgary",
      owner: "Nathan Rivera",
      price: "$1,250,000",
      bedrooms: 4,
      bathrooms: 3,
      location: { latitude: 51.044733, longitude: -114.071883 },
    },
    {
      id: 9,
      name: "Parkside Bungalow",
      city: "Montreal",
      owner: "Liam Fisher",
      price: "$900,000",
      bedrooms: 3,
      bathrooms: 2,
      location: { latitude: 45.509062, longitude: -73.554709 },
    },
    {
      id: 10,
      name: "Bayview Penthouse",
      city: "Toronto",
      owner: "Sophia Taylor",
      price: "$2,100,000",
      bedrooms: 2,
      bathrooms: 2,
      location: { latitude: 43.65107, longitude: -79.347015 },
    },
    {
      id: 11,
      name: "Forest Retreat",
      city: "Ottawa",
      owner: "William Harris",
      price: "$1,000,000",
      bedrooms: 4,
      bathrooms: 3,
      location: { latitude: 45.4215, longitude: -75.6972 },
    },
    {
      id: 12,
      name: "Lakeside Paradise",
      city: "Vancouver",
      owner: "Isabella White",
      price: "$1,700,000",
      bedrooms: 5,
      bathrooms: 4,
      location: { latitude: 49.2827, longitude: -123.1207 },
    },
    {
      id: 13,
      name: "Urban Haven",
      city: "Montreal",
      owner: "Charlotte Black",
      price: "$950,000",
      bedrooms: 3,
      bathrooms: 3,
      location: { latitude: 45.5088, longitude: -73.554 },
    },
    {
      id: 14,
      name: "Horizon View Apartments",
      city: "Calgary",
      owner: "James Green",
      price: "$800,000",
      bedrooms: 2,
      bathrooms: 2,
      location: { latitude: 51.0447, longitude: -114.0719 },
    },
    {
      id: 15,
      name: "Riverside Mansion",
      city: "Toronto",
      owner: "Emily Thompson",
      price: "$2,500,000",
      bedrooms: 6,
      bathrooms: 5,
      location: { latitude: 43.70011, longitude: -79.4163 },
    },
  ];
  
  export default propertyData;
  